name: Test OIDC Token AuthN and AuthZ with Artifactory

on:
  workflow_dispatch:

# This is required as per
# https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-cloud-providers#adding-permissions-settings
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OIDC_AUDIENCE: 'jfrog-github'
      JF_OIDC_PROVIDER_NAME: "github-oidc-integration"
      JFROG_BUILD_STATUS: PASS

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Replace with your desired Java version
          distribution: 'temurin'

      - name: Install OIDC Client from Core Package
        run: npm install @actions/core @actions/http-client

      - name: Install JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3
        env:
          JF_URL: ${{ vars.JF_URL }}
        with:
          oidc-provider-name: ${{ env.JF_OIDC_PROVIDER_NAME }}
          oidc-audience: ${{ env.OIDC_AUDIENCE }}


      - name: Test JF CLI
        run: |
          jf c show
          jf rt ping
          jf rt curl -XGET /api/build
          jf rt curl -XPOST /api/foo -d '{}'
